2018-06-13 15:12:27,045 [1] mfe_gui.frmMain.frmMain_Load(C:\BA\Software_projects\PIC\1510\8.5.18_ver_1_f\BA1510_GUI_1.1.11\MFE_gui\frmMain.cs:70) [INFO] - Statring Program, Version - 1.1.11.0, AtpLib - 1.4.4.0
2018-06-13 15:12:27,060 [1] mfe_gui.frmMain.loadDefaultcomPort(C:\BA\Software_projects\PIC\1510\8.5.18_ver_1_f\BA1510_GUI_1.1.11\MFE_gui\frmMain.cs:164) [INFO] - could not read defualt comport from configuration, using COM1 as defualt
2018-06-13 15:12:28,887 [1] atpLib.Devices.SerialDevice.connect(C:\BA\Software_projects\PIC\1510\8.5.18_ver_1_f\BA1510_GUI_1.1.11\atpLib\Devices\SerialDevice.cs:46) [ERROR] - error oppening port "COM1"
System.IO.IOException: The port 'COM1' does not exist.
   at System.IO.Ports.InternalResources.WinIOError(Int32 errorCode, String str)
   at System.IO.Ports.SerialStream..ctor(String portName, Int32 baudRate, Parity parity, Int32 dataBits, StopBits stopBits, Int32 readTimeout, Int32 writeTimeout, Handshake handshake, Boolean dtrEnable, Boolean rtsEnable, Boolean discardNull, Byte parityReplace)
   at System.IO.Ports.SerialPort.Open()
   at atpLib.Devices.SerialDevice.connect() in C:\BA\Software_projects\PIC\1510\8.5.18_ver_1_f\BA1510_GUI_1.1.11\atpLib\Devices\SerialDevice.cs:line 41
2018-06-13 15:12:52,402 [4] atpLib.Scenarios.Scenario.runTask(C:\BA\Software_projects\PIC\1510\8.5.18_ver_1_f\BA1510_GUI_1.1.11\atpLib\Scenarios\Scenario.cs:178) [INFO] - Running scenario "Software Update Scenario" - with timeout of: 2147483 seconds.
2018-06-13 15:12:52,418 [5] mfe_gui.Scenarios.SoftwareUpdateScenario.internalRun(C:\BA\Software_projects\PIC\1510\8.5.18_ver_1_f\BA1510_GUI_1.1.11\MFE_gui\Scenarios\SoftwareUpdateScenario.cs:66) [INFO] - Programming address: 0x2000
2018-06-13 15:12:52,433 [6] atpLib.Scenarios.Scenario.runTask(C:\BA\Software_projects\PIC\1510\8.5.18_ver_1_f\BA1510_GUI_1.1.11\atpLib\Scenarios\Scenario.cs:178) [INFO] - Running scenario "Send Line Scenario" - with timeout of: 10 seconds.
2018-06-13 15:12:52,433 [7] atpLib.Scenarios.SingleMessageSingleDeviceScenario.internalRun(C:\BA\Software_projects\PIC\1510\8.5.18_ver_1_f\BA1510_GUI_1.1.11\atpLib\Scenarios\SingleMessageSingleDeviceScenario.cs:27) [INFO] - sending a message of type: SetBootDataMessage
2018-06-13 15:12:52,433 [7] atpLib.Devices.RFC1662BinarySerialDevice.sendMsg(C:\BA\Software_projects\PIC\1510\8.5.18_ver_1_f\BA1510_GUI_1.1.11\atpLib\Devices\RFC1662Device\RFC1662BinarySerialDevice.cs:107) [INFO] - sending 6
2018-06-13 15:12:52,449 [7] atpLib.Scenarios.SingleMessageSingleDeviceScenario.internalRun(C:\BA\Software_projects\PIC\1510\8.5.18_ver_1_f\BA1510_GUI_1.1.11\atpLib\Scenarios\SingleMessageSingleDeviceScenario.cs:68) [ERROR] - The port is closed.
2018-06-13 15:12:52,543 [5] atpLib.Scenarios.Scenario.run(C:\BA\Software_projects\PIC\1510\8.5.18_ver_1_f\BA1510_GUI_1.1.11\atpLib\Scenarios\Scenario.cs:126) [ERROR] - Internal Scenario Error
System.InvalidOperationException: The port is closed.
   at atpLib.Scenarios.SingleMessageSingleDeviceScenario.internalRun(CancellationToken ct) in C:\BA\Software_projects\PIC\1510\8.5.18_ver_1_f\BA1510_GUI_1.1.11\atpLib\Scenarios\SingleMessageSingleDeviceScenario.cs:line 69
   at atpLib.Scenarios.Scenario.<>c__DisplayClass23_0.<runTask>b__0() in C:\BA\Software_projects\PIC\1510\8.5.18_ver_1_f\BA1510_GUI_1.1.11\atpLib\Scenarios\Scenario.cs:line 180
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
2018-06-13 15:12:52,543 [5] mfe_gui.Scenarios.SoftwareUpdateScenario.internalRun(C:\BA\Software_projects\PIC\1510\8.5.18_ver_1_f\BA1510_GUI_1.1.11\MFE_gui\Scenarios\SoftwareUpdateScenario.cs:137) [ERROR] - error in "Software Update Scenario"
mfe_gui.Scenarios.SoftwareUpdateScenario+SoftwareUpdateException: Exception of type 'mfe_gui.Scenarios.SoftwareUpdateScenario+SoftwareUpdateException' was thrown.
   at mfe_gui.Scenarios.SoftwareUpdateScenario.internalRun(CancellationToken ct) in C:\BA\Software_projects\PIC\1510\8.5.18_ver_1_f\BA1510_GUI_1.1.11\MFE_gui\Scenarios\SoftwareUpdateScenario.cs:line 70
2018-06-13 15:12:52,558 [4] atpLib.Scenarios.Scenario.runTask(C:\BA\Software_projects\PIC\1510\8.5.18_ver_1_f\BA1510_GUI_1.1.11\atpLib\Scenarios\Scenario.cs:221) [INFO] - Scenario failed.
2018-06-13 15:12:55,908 [6] atpLib.Scenarios.Scenario.runTask(C:\BA\Software_projects\PIC\1510\8.5.18_ver_1_f\BA1510_GUI_1.1.11\atpLib\Scenarios\Scenario.cs:178) [INFO] - Running scenario "Software Update Scenario" - with timeout of: 2147483 seconds.
2018-06-13 15:12:55,924 [4] mfe_gui.Scenarios.SoftwareUpdateScenario.internalRun(C:\BA\Software_projects\PIC\1510\8.5.18_ver_1_f\BA1510_GUI_1.1.11\MFE_gui\Scenarios\SoftwareUpdateScenario.cs:66) [INFO] - Programming address: 0x2000
2018-06-13 15:12:55,924 [5] atpLib.Scenarios.Scenario.runTask(C:\BA\Software_projects\PIC\1510\8.5.18_ver_1_f\BA1510_GUI_1.1.11\atpLib\Scenarios\Scenario.cs:178) [INFO] - Running scenario "Send Line Scenario" - with timeout of: 10 seconds.
2018-06-13 15:12:55,924 [7] atpLib.Scenarios.SingleMessageSingleDeviceScenario.internalRun(C:\BA\Software_projects\PIC\1510\8.5.18_ver_1_f\BA1510_GUI_1.1.11\atpLib\Scenarios\SingleMessageSingleDeviceScenario.cs:27) [INFO] - sending a message of type: SetBootDataMessage
2018-06-13 15:12:55,924 [7] atpLib.Devices.RFC1662BinarySerialDevice.sendMsg(C:\BA\Software_projects\PIC\1510\8.5.18_ver_1_f\BA1510_GUI_1.1.11\atpLib\Devices\RFC1662Device\RFC1662BinarySerialDevice.cs:107) [INFO] - sending 6
2018-06-13 15:12:55,924 [7] atpLib.Scenarios.SingleMessageSingleDeviceScenario.internalRun(C:\BA\Software_projects\PIC\1510\8.5.18_ver_1_f\BA1510_GUI_1.1.11\atpLib\Scenarios\SingleMessageSingleDeviceScenario.cs:68) [ERROR] - The port is closed.
2018-06-13 15:12:55,955 [4] atpLib.Scenarios.Scenario.run(C:\BA\Software_projects\PIC\1510\8.5.18_ver_1_f\BA1510_GUI_1.1.11\atpLib\Scenarios\Scenario.cs:126) [ERROR] - Internal Scenario Error
System.InvalidOperationException: The port is closed.
   at atpLib.Scenarios.SingleMessageSingleDeviceScenario.internalRun(CancellationToken ct) in C:\BA\Software_projects\PIC\1510\8.5.18_ver_1_f\BA1510_GUI_1.1.11\atpLib\Scenarios\SingleMessageSingleDeviceScenario.cs:line 69
   at atpLib.Scenarios.Scenario.<>c__DisplayClass23_0.<runTask>b__0() in C:\BA\Software_projects\PIC\1510\8.5.18_ver_1_f\BA1510_GUI_1.1.11\atpLib\Scenarios\Scenario.cs:line 180
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
2018-06-13 15:12:55,955 [4] mfe_gui.Scenarios.SoftwareUpdateScenario.internalRun(C:\BA\Software_projects\PIC\1510\8.5.18_ver_1_f\BA1510_GUI_1.1.11\MFE_gui\Scenarios\SoftwareUpdateScenario.cs:137) [ERROR] - error in "Software Update Scenario"
mfe_gui.Scenarios.SoftwareUpdateScenario+SoftwareUpdateException: Exception of type 'mfe_gui.Scenarios.SoftwareUpdateScenario+SoftwareUpdateException' was thrown.
   at mfe_gui.Scenarios.SoftwareUpdateScenario.internalRun(CancellationToken ct) in C:\BA\Software_projects\PIC\1510\8.5.18_ver_1_f\BA1510_GUI_1.1.11\MFE_gui\Scenarios\SoftwareUpdateScenario.cs:line 70
2018-06-13 15:12:55,971 [6] atpLib.Scenarios.Scenario.runTask(C:\BA\Software_projects\PIC\1510\8.5.18_ver_1_f\BA1510_GUI_1.1.11\atpLib\Scenarios\Scenario.cs:221) [INFO] - Scenario failed.
2018-06-13 15:12:57,808 [7] atpLib.Scenarios.Scenario.runTask(C:\BA\Software_projects\PIC\1510\8.5.18_ver_1_f\BA1510_GUI_1.1.11\atpLib\Scenarios\Scenario.cs:178) [INFO] - Running scenario "Software Update Scenario" - with timeout of: 2147483 seconds.
2018-06-13 15:12:57,839 [6] mfe_gui.Scenarios.SoftwareUpdateScenario.internalRun(C:\BA\Software_projects\PIC\1510\8.5.18_ver_1_f\BA1510_GUI_1.1.11\MFE_gui\Scenarios\SoftwareUpdateScenario.cs:66) [INFO] - Programming address: 0x2000
2018-06-13 15:12:57,839 [5] atpLib.Scenarios.Scenario.runTask(C:\BA\Software_projects\PIC\1510\8.5.18_ver_1_f\BA1510_GUI_1.1.11\atpLib\Scenarios\Scenario.cs:178) [INFO] - Running scenario "Send Line Scenario" - with timeout of: 10 seconds.
2018-06-13 15:12:57,839 [4] atpLib.Scenarios.SingleMessageSingleDeviceScenario.internalRun(C:\BA\Software_projects\PIC\1510\8.5.18_ver_1_f\BA1510_GUI_1.1.11\atpLib\Scenarios\SingleMessageSingleDeviceScenario.cs:27) [INFO] - sending a message of type: SetBootDataMessage
2018-06-13 15:12:57,839 [4] atpLib.Devices.RFC1662BinarySerialDevice.sendMsg(C:\BA\Software_projects\PIC\1510\8.5.18_ver_1_f\BA1510_GUI_1.1.11\atpLib\Devices\RFC1662Device\RFC1662BinarySerialDevice.cs:107) [INFO] - sending 6
2018-06-13 15:12:57,839 [4] atpLib.Scenarios.SingleMessageSingleDeviceScenario.internalRun(C:\BA\Software_projects\PIC\1510\8.5.18_ver_1_f\BA1510_GUI_1.1.11\atpLib\Scenarios\SingleMessageSingleDeviceScenario.cs:68) [ERROR] - The port is closed.
2018-06-13 15:12:57,871 [6] atpLib.Scenarios.Scenario.run(C:\BA\Software_projects\PIC\1510\8.5.18_ver_1_f\BA1510_GUI_1.1.11\atpLib\Scenarios\Scenario.cs:126) [ERROR] - Internal Scenario Error
System.InvalidOperationException: The port is closed.
   at atpLib.Scenarios.SingleMessageSingleDeviceScenario.internalRun(CancellationToken ct) in C:\BA\Software_projects\PIC\1510\8.5.18_ver_1_f\BA1510_GUI_1.1.11\atpLib\Scenarios\SingleMessageSingleDeviceScenario.cs:line 69
   at atpLib.Scenarios.Scenario.<>c__DisplayClass23_0.<runTask>b__0() in C:\BA\Software_projects\PIC\1510\8.5.18_ver_1_f\BA1510_GUI_1.1.11\atpLib\Scenarios\Scenario.cs:line 180
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
2018-06-13 15:12:57,871 [6] mfe_gui.Scenarios.SoftwareUpdateScenario.internalRun(C:\BA\Software_projects\PIC\1510\8.5.18_ver_1_f\BA1510_GUI_1.1.11\MFE_gui\Scenarios\SoftwareUpdateScenario.cs:137) [ERROR] - error in "Software Update Scenario"
mfe_gui.Scenarios.SoftwareUpdateScenario+SoftwareUpdateException: Exception of type 'mfe_gui.Scenarios.SoftwareUpdateScenario+SoftwareUpdateException' was thrown.
   at mfe_gui.Scenarios.SoftwareUpdateScenario.internalRun(CancellationToken ct) in C:\BA\Software_projects\PIC\1510\8.5.18_ver_1_f\BA1510_GUI_1.1.11\MFE_gui\Scenarios\SoftwareUpdateScenario.cs:line 70
2018-06-13 15:12:57,886 [7] atpLib.Scenarios.Scenario.runTask(C:\BA\Software_projects\PIC\1510\8.5.18_ver_1_f\BA1510_GUI_1.1.11\atpLib\Scenarios\Scenario.cs:221) [INFO] - Scenario failed.
2018-06-13 15:12:58,721 [6] atpLib.Scenarios.Scenario.runTask(C:\BA\Software_projects\PIC\1510\8.5.18_ver_1_f\BA1510_GUI_1.1.11\atpLib\Scenarios\Scenario.cs:178) [INFO] - Running scenario "Software Update Scenario" - with timeout of: 2147483 seconds.
2018-06-13 15:12:58,736 [7] mfe_gui.Scenarios.SoftwareUpdateScenario.internalRun(C:\BA\Software_projects\PIC\1510\8.5.18_ver_1_f\BA1510_GUI_1.1.11\MFE_gui\Scenarios\SoftwareUpdateScenario.cs:66) [INFO] - Programming address: 0x2000
2018-06-13 15:12:58,736 [4] atpLib.Scenarios.Scenario.runTask(C:\BA\Software_projects\PIC\1510\8.5.18_ver_1_f\BA1510_GUI_1.1.11\atpLib\Scenarios\Scenario.cs:178) [INFO] - Running scenario "Send Line Scenario" - with timeout of: 10 seconds.
2018-06-13 15:12:58,736 [5] atpLib.Scenarios.SingleMessageSingleDeviceScenario.internalRun(C:\BA\Software_projects\PIC\1510\8.5.18_ver_1_f\BA1510_GUI_1.1.11\atpLib\Scenarios\SingleMessageSingleDeviceScenario.cs:27) [INFO] - sending a message of type: SetBootDataMessage
2018-06-13 15:12:58,736 [5] atpLib.Devices.RFC1662BinarySerialDevice.sendMsg(C:\BA\Software_projects\PIC\1510\8.5.18_ver_1_f\BA1510_GUI_1.1.11\atpLib\Devices\RFC1662Device\RFC1662BinarySerialDevice.cs:107) [INFO] - sending 6
2018-06-13 15:12:58,736 [5] atpLib.Scenarios.SingleMessageSingleDeviceScenario.internalRun(C:\BA\Software_projects\PIC\1510\8.5.18_ver_1_f\BA1510_GUI_1.1.11\atpLib\Scenarios\SingleMessageSingleDeviceScenario.cs:68) [ERROR] - The port is closed.
2018-06-13 15:12:58,767 [7] atpLib.Scenarios.Scenario.run(C:\BA\Software_projects\PIC\1510\8.5.18_ver_1_f\BA1510_GUI_1.1.11\atpLib\Scenarios\Scenario.cs:126) [ERROR] - Internal Scenario Error
System.InvalidOperationException: The port is closed.
   at atpLib.Scenarios.SingleMessageSingleDeviceScenario.internalRun(CancellationToken ct) in C:\BA\Software_projects\PIC\1510\8.5.18_ver_1_f\BA1510_GUI_1.1.11\atpLib\Scenarios\SingleMessageSingleDeviceScenario.cs:line 69
   at atpLib.Scenarios.Scenario.<>c__DisplayClass23_0.<runTask>b__0() in C:\BA\Software_projects\PIC\1510\8.5.18_ver_1_f\BA1510_GUI_1.1.11\atpLib\Scenarios\Scenario.cs:line 180
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
2018-06-13 15:12:58,767 [7] mfe_gui.Scenarios.SoftwareUpdateScenario.internalRun(C:\BA\Software_projects\PIC\1510\8.5.18_ver_1_f\BA1510_GUI_1.1.11\MFE_gui\Scenarios\SoftwareUpdateScenario.cs:137) [ERROR] - error in "Software Update Scenario"
mfe_gui.Scenarios.SoftwareUpdateScenario+SoftwareUpdateException: Exception of type 'mfe_gui.Scenarios.SoftwareUpdateScenario+SoftwareUpdateException' was thrown.
   at mfe_gui.Scenarios.SoftwareUpdateScenario.internalRun(CancellationToken ct) in C:\BA\Software_projects\PIC\1510\8.5.18_ver_1_f\BA1510_GUI_1.1.11\MFE_gui\Scenarios\SoftwareUpdateScenario.cs:line 70
2018-06-13 15:12:58,783 [6] atpLib.Scenarios.Scenario.runTask(C:\BA\Software_projects\PIC\1510\8.5.18_ver_1_f\BA1510_GUI_1.1.11\atpLib\Scenarios\Scenario.cs:221) [INFO] - Scenario failed.
2018-06-13 15:12:59,914 [5] atpLib.Scenarios.Scenario.runTask(C:\BA\Software_projects\PIC\1510\8.5.18_ver_1_f\BA1510_GUI_1.1.11\atpLib\Scenarios\Scenario.cs:178) [INFO] - Running scenario "Software Update Scenario" - with timeout of: 2147483 seconds.
2018-06-13 15:12:59,930 [7] mfe_gui.Scenarios.SoftwareUpdateScenario.internalRun(C:\BA\Software_projects\PIC\1510\8.5.18_ver_1_f\BA1510_GUI_1.1.11\MFE_gui\Scenarios\SoftwareUpdateScenario.cs:66) [INFO] - Programming address: 0x2000
2018-06-13 15:12:59,930 [6] atpLib.Scenarios.Scenario.runTask(C:\BA\Software_projects\PIC\1510\8.5.18_ver_1_f\BA1510_GUI_1.1.11\atpLib\Scenarios\Scenario.cs:178) [INFO] - Running scenario "Send Line Scenario" - with timeout of: 10 seconds.
2018-06-13 15:12:59,930 [4] atpLib.Scenarios.SingleMessageSingleDeviceScenario.internalRun(C:\BA\Software_projects\PIC\1510\8.5.18_ver_1_f\BA1510_GUI_1.1.11\atpLib\Scenarios\SingleMessageSingleDeviceScenario.cs:27) [INFO] - sending a message of type: SetBootDataMessage
2018-06-13 15:12:59,930 [4] atpLib.Devices.RFC1662BinarySerialDevice.sendMsg(C:\BA\Software_projects\PIC\1510\8.5.18_ver_1_f\BA1510_GUI_1.1.11\atpLib\Devices\RFC1662Device\RFC1662BinarySerialDevice.cs:107) [INFO] - sending 6
2018-06-13 15:12:59,930 [4] atpLib.Scenarios.SingleMessageSingleDeviceScenario.internalRun(C:\BA\Software_projects\PIC\1510\8.5.18_ver_1_f\BA1510_GUI_1.1.11\atpLib\Scenarios\SingleMessageSingleDeviceScenario.cs:68) [ERROR] - The port is closed.
2018-06-13 15:12:59,961 [7] atpLib.Scenarios.Scenario.run(C:\BA\Software_projects\PIC\1510\8.5.18_ver_1_f\BA1510_GUI_1.1.11\atpLib\Scenarios\Scenario.cs:126) [ERROR] - Internal Scenario Error
System.InvalidOperationException: The port is closed.
   at atpLib.Scenarios.SingleMessageSingleDeviceScenario.internalRun(CancellationToken ct) in C:\BA\Software_projects\PIC\1510\8.5.18_ver_1_f\BA1510_GUI_1.1.11\atpLib\Scenarios\SingleMessageSingleDeviceScenario.cs:line 69
   at atpLib.Scenarios.Scenario.<>c__DisplayClass23_0.<runTask>b__0() in C:\BA\Software_projects\PIC\1510\8.5.18_ver_1_f\BA1510_GUI_1.1.11\atpLib\Scenarios\Scenario.cs:line 180
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
2018-06-13 15:12:59,961 [7] mfe_gui.Scenarios.SoftwareUpdateScenario.internalRun(C:\BA\Software_projects\PIC\1510\8.5.18_ver_1_f\BA1510_GUI_1.1.11\MFE_gui\Scenarios\SoftwareUpdateScenario.cs:137) [ERROR] - error in "Software Update Scenario"
mfe_gui.Scenarios.SoftwareUpdateScenario+SoftwareUpdateException: Exception of type 'mfe_gui.Scenarios.SoftwareUpdateScenario+SoftwareUpdateException' was thrown.
   at mfe_gui.Scenarios.SoftwareUpdateScenario.internalRun(CancellationToken ct) in C:\BA\Software_projects\PIC\1510\8.5.18_ver_1_f\BA1510_GUI_1.1.11\MFE_gui\Scenarios\SoftwareUpdateScenario.cs:line 70
2018-06-13 15:12:59,977 [5] atpLib.Scenarios.Scenario.runTask(C:\BA\Software_projects\PIC\1510\8.5.18_ver_1_f\BA1510_GUI_1.1.11\atpLib\Scenarios\Scenario.cs:221) [INFO] - Scenario failed.
2018-06-13 15:13:01,244 [6] atpLib.Scenarios.Scenario.runTask(C:\BA\Software_projects\PIC\1510\8.5.18_ver_1_f\BA1510_GUI_1.1.11\atpLib\Scenarios\Scenario.cs:178) [INFO] - Running scenario "Software Update Scenario" - with timeout of: 2147483 seconds.
2018-06-13 15:13:01,276 [4] mfe_gui.Scenarios.SoftwareUpdateScenario.internalRun(C:\BA\Software_projects\PIC\1510\8.5.18_ver_1_f\BA1510_GUI_1.1.11\MFE_gui\Scenarios\SoftwareUpdateScenario.cs:66) [INFO] - Programming address: 0x2000
2018-06-13 15:13:01,279 [9] atpLib.Scenarios.Scenario.runTask(C:\BA\Software_projects\PIC\1510\8.5.18_ver_1_f\BA1510_GUI_1.1.11\atpLib\Scenarios\Scenario.cs:178) [INFO] - Running scenario "Send Line Scenario" - with timeout of: 10 seconds.
2018-06-13 15:13:01,280 [5] atpLib.Scenarios.SingleMessageSingleDeviceScenario.internalRun(C:\BA\Software_projects\PIC\1510\8.5.18_ver_1_f\BA1510_GUI_1.1.11\atpLib\Scenarios\SingleMessageSingleDeviceScenario.cs:27) [INFO] - sending a message of type: SetBootDataMessage
2018-06-13 15:13:01,280 [5] atpLib.Devices.RFC1662BinarySerialDevice.sendMsg(C:\BA\Software_projects\PIC\1510\8.5.18_ver_1_f\BA1510_GUI_1.1.11\atpLib\Devices\RFC1662Device\RFC1662BinarySerialDevice.cs:107) [INFO] - sending 6
2018-06-13 15:13:01,280 [5] atpLib.Scenarios.SingleMessageSingleDeviceScenario.internalRun(C:\BA\Software_projects\PIC\1510\8.5.18_ver_1_f\BA1510_GUI_1.1.11\atpLib\Scenarios\SingleMessageSingleDeviceScenario.cs:68) [ERROR] - The port is closed.
2018-06-13 15:13:01,311 [4] atpLib.Scenarios.Scenario.run(C:\BA\Software_projects\PIC\1510\8.5.18_ver_1_f\BA1510_GUI_1.1.11\atpLib\Scenarios\Scenario.cs:126) [ERROR] - Internal Scenario Error
System.InvalidOperationException: The port is closed.
   at atpLib.Scenarios.SingleMessageSingleDeviceScenario.internalRun(CancellationToken ct) in C:\BA\Software_projects\PIC\1510\8.5.18_ver_1_f\BA1510_GUI_1.1.11\atpLib\Scenarios\SingleMessageSingleDeviceScenario.cs:line 69
   at atpLib.Scenarios.Scenario.<>c__DisplayClass23_0.<runTask>b__0() in C:\BA\Software_projects\PIC\1510\8.5.18_ver_1_f\BA1510_GUI_1.1.11\atpLib\Scenarios\Scenario.cs:line 180
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
2018-06-13 15:13:01,311 [4] mfe_gui.Scenarios.SoftwareUpdateScenario.internalRun(C:\BA\Software_projects\PIC\1510\8.5.18_ver_1_f\BA1510_GUI_1.1.11\MFE_gui\Scenarios\SoftwareUpdateScenario.cs:137) [ERROR] - error in "Software Update Scenario"
mfe_gui.Scenarios.SoftwareUpdateScenario+SoftwareUpdateException: Exception of type 'mfe_gui.Scenarios.SoftwareUpdateScenario+SoftwareUpdateException' was thrown.
   at mfe_gui.Scenarios.SoftwareUpdateScenario.internalRun(CancellationToken ct) in C:\BA\Software_projects\PIC\1510\8.5.18_ver_1_f\BA1510_GUI_1.1.11\MFE_gui\Scenarios\SoftwareUpdateScenario.cs:line 70
2018-06-13 15:13:01,327 [6] atpLib.Scenarios.Scenario.runTask(C:\BA\Software_projects\PIC\1510\8.5.18_ver_1_f\BA1510_GUI_1.1.11\atpLib\Scenarios\Scenario.cs:221) [INFO] - Scenario failed.
2018-06-13 15:13:02,155 [9] atpLib.Scenarios.Scenario.runTask(C:\BA\Software_projects\PIC\1510\8.5.18_ver_1_f\BA1510_GUI_1.1.11\atpLib\Scenarios\Scenario.cs:178) [INFO] - Running scenario "Software Update Scenario" - with timeout of: 2147483 seconds.
2018-06-13 15:13:02,170 [5] mfe_gui.Scenarios.SoftwareUpdateScenario.internalRun(C:\BA\Software_projects\PIC\1510\8.5.18_ver_1_f\BA1510_GUI_1.1.11\MFE_gui\Scenarios\SoftwareUpdateScenario.cs:66) [INFO] - Programming address: 0x2000
2018-06-13 15:13:02,170 [4] atpLib.Scenarios.Scenario.runTask(C:\BA\Software_projects\PIC\1510\8.5.18_ver_1_f\BA1510_GUI_1.1.11\atpLib\Scenarios\Scenario.cs:178) [INFO] - Running scenario "Send Line Scenario" - with timeout of: 10 seconds.
2018-06-13 15:13:02,170 [6] atpLib.Scenarios.SingleMessageSingleDeviceScenario.internalRun(C:\BA\Software_projects\PIC\1510\8.5.18_ver_1_f\BA1510_GUI_1.1.11\atpLib\Scenarios\SingleMessageSingleDeviceScenario.cs:27) [INFO] - sending a message of type: SetBootDataMessage
2018-06-13 15:13:02,170 [6] atpLib.Devices.RFC1662BinarySerialDevice.sendMsg(C:\BA\Software_projects\PIC\1510\8.5.18_ver_1_f\BA1510_GUI_1.1.11\atpLib\Devices\RFC1662Device\RFC1662BinarySerialDevice.cs:107) [INFO] - sending 6
2018-06-13 15:13:02,170 [6] atpLib.Scenarios.SingleMessageSingleDeviceScenario.internalRun(C:\BA\Software_projects\PIC\1510\8.5.18_ver_1_f\BA1510_GUI_1.1.11\atpLib\Scenarios\SingleMessageSingleDeviceScenario.cs:68) [ERROR] - The port is closed.
2018-06-13 15:13:02,202 [5] atpLib.Scenarios.Scenario.run(C:\BA\Software_projects\PIC\1510\8.5.18_ver_1_f\BA1510_GUI_1.1.11\atpLib\Scenarios\Scenario.cs:126) [ERROR] - Internal Scenario Error
System.InvalidOperationException: The port is closed.
   at atpLib.Scenarios.SingleMessageSingleDeviceScenario.internalRun(CancellationToken ct) in C:\BA\Software_projects\PIC\1510\8.5.18_ver_1_f\BA1510_GUI_1.1.11\atpLib\Scenarios\SingleMessageSingleDeviceScenario.cs:line 69
   at atpLib.Scenarios.Scenario.<>c__DisplayClass23_0.<runTask>b__0() in C:\BA\Software_projects\PIC\1510\8.5.18_ver_1_f\BA1510_GUI_1.1.11\atpLib\Scenarios\Scenario.cs:line 180
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
2018-06-13 15:13:02,202 [5] mfe_gui.Scenarios.SoftwareUpdateScenario.internalRun(C:\BA\Software_projects\PIC\1510\8.5.18_ver_1_f\BA1510_GUI_1.1.11\MFE_gui\Scenarios\SoftwareUpdateScenario.cs:137) [ERROR] - error in "Software Update Scenario"
mfe_gui.Scenarios.SoftwareUpdateScenario+SoftwareUpdateException: Exception of type 'mfe_gui.Scenarios.SoftwareUpdateScenario+SoftwareUpdateException' was thrown.
   at mfe_gui.Scenarios.SoftwareUpdateScenario.internalRun(CancellationToken ct) in C:\BA\Software_projects\PIC\1510\8.5.18_ver_1_f\BA1510_GUI_1.1.11\MFE_gui\Scenarios\SoftwareUpdateScenario.cs:line 70
2018-06-13 15:13:02,217 [9] atpLib.Scenarios.Scenario.runTask(C:\BA\Software_projects\PIC\1510\8.5.18_ver_1_f\BA1510_GUI_1.1.11\atpLib\Scenarios\Scenario.cs:221) [INFO] - Scenario failed.
2018-06-13 15:13:08,629 [7] atpLib.Scenarios.Scenario.runTask(C:\BA\Software_projects\PIC\1510\8.5.18_ver_1_f\BA1510_GUI_1.1.11\atpLib\Scenarios\Scenario.cs:178) [INFO] - Running scenario "Software Update Scenario" - with timeout of: 2147483 seconds.
2018-06-13 15:13:08,636 [9] mfe_gui.Scenarios.SoftwareUpdateScenario.internalRun(C:\BA\Software_projects\PIC\1510\8.5.18_ver_1_f\BA1510_GUI_1.1.11\MFE_gui\Scenarios\SoftwareUpdateScenario.cs:66) [INFO] - Programming address: 0x2000
2018-06-13 15:13:08,638 [4] atpLib.Scenarios.Scenario.runTask(C:\BA\Software_projects\PIC\1510\8.5.18_ver_1_f\BA1510_GUI_1.1.11\atpLib\Scenarios\Scenario.cs:178) [INFO] - Running scenario "Send Line Scenario" - with timeout of: 10 seconds.
2018-06-13 15:13:08,641 [5] atpLib.Scenarios.SingleMessageSingleDeviceScenario.internalRun(C:\BA\Software_projects\PIC\1510\8.5.18_ver_1_f\BA1510_GUI_1.1.11\atpLib\Scenarios\SingleMessageSingleDeviceScenario.cs:27) [INFO] - sending a message of type: SetBootDataMessage
2018-06-13 15:13:08,643 [5] atpLib.Devices.RFC1662BinarySerialDevice.sendMsg(C:\BA\Software_projects\PIC\1510\8.5.18_ver_1_f\BA1510_GUI_1.1.11\atpLib\Devices\RFC1662Device\RFC1662BinarySerialDevice.cs:107) [INFO] - sending 6
2018-06-13 15:13:08,645 [5] atpLib.Scenarios.SingleMessageSingleDeviceScenario.internalRun(C:\BA\Software_projects\PIC\1510\8.5.18_ver_1_f\BA1510_GUI_1.1.11\atpLib\Scenarios\SingleMessageSingleDeviceScenario.cs:68) [ERROR] - The port is closed.
2018-06-13 15:13:08,651 [9] atpLib.Scenarios.Scenario.run(C:\BA\Software_projects\PIC\1510\8.5.18_ver_1_f\BA1510_GUI_1.1.11\atpLib\Scenarios\Scenario.cs:126) [ERROR] - Internal Scenario Error
System.InvalidOperationException: The port is closed.
   at atpLib.Scenarios.SingleMessageSingleDeviceScenario.internalRun(CancellationToken ct) in C:\BA\Software_projects\PIC\1510\8.5.18_ver_1_f\BA1510_GUI_1.1.11\atpLib\Scenarios\SingleMessageSingleDeviceScenario.cs:line 69
   at atpLib.Scenarios.Scenario.<>c__DisplayClass23_0.<runTask>b__0() in C:\BA\Software_projects\PIC\1510\8.5.18_ver_1_f\BA1510_GUI_1.1.11\atpLib\Scenarios\Scenario.cs:line 180
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
2018-06-13 15:13:08,654 [9] mfe_gui.Scenarios.SoftwareUpdateScenario.internalRun(C:\BA\Software_projects\PIC\1510\8.5.18_ver_1_f\BA1510_GUI_1.1.11\MFE_gui\Scenarios\SoftwareUpdateScenario.cs:137) [ERROR] - error in "Software Update Scenario"
mfe_gui.Scenarios.SoftwareUpdateScenario+SoftwareUpdateException: Exception of type 'mfe_gui.Scenarios.SoftwareUpdateScenario+SoftwareUpdateException' was thrown.
   at mfe_gui.Scenarios.SoftwareUpdateScenario.internalRun(CancellationToken ct) in C:\BA\Software_projects\PIC\1510\8.5.18_ver_1_f\BA1510_GUI_1.1.11\MFE_gui\Scenarios\SoftwareUpdateScenario.cs:line 70
2018-06-13 15:13:08,669 [7] atpLib.Scenarios.Scenario.runTask(C:\BA\Software_projects\PIC\1510\8.5.18_ver_1_f\BA1510_GUI_1.1.11\atpLib\Scenarios\Scenario.cs:221) [INFO] - Scenario failed.
2018-06-13 15:20:35,553 [23] atpLib.Scenarios.Scenario.runTask(C:\BA\Software_projects\PIC\1510\8.5.18_ver_1_f\BA1510_GUI_1.1.11\atpLib\Scenarios\Scenario.cs:178) [INFO] - Running scenario "Software Update Scenario" - with timeout of: 2147483 seconds.
2018-06-13 15:20:35,584 [24] mfe_gui.Scenarios.SoftwareUpdateScenario.internalRun(C:\BA\Software_projects\PIC\1510\8.5.18_ver_1_f\BA1510_GUI_1.1.11\MFE_gui\Scenarios\SoftwareUpdateScenario.cs:66) [INFO] - Programming address: 0x2000
2018-06-13 15:20:35,584 [25] atpLib.Scenarios.Scenario.runTask(C:\BA\Software_projects\PIC\1510\8.5.18_ver_1_f\BA1510_GUI_1.1.11\atpLib\Scenarios\Scenario.cs:178) [INFO] - Running scenario "Send Line Scenario" - with timeout of: 10 seconds.
2018-06-13 15:20:35,584 [26] atpLib.Scenarios.SingleMessageSingleDeviceScenario.internalRun(C:\BA\Software_projects\PIC\1510\8.5.18_ver_1_f\BA1510_GUI_1.1.11\atpLib\Scenarios\SingleMessageSingleDeviceScenario.cs:27) [INFO] - sending a message of type: SetBootDataMessage
2018-06-13 15:20:35,584 [26] atpLib.Devices.RFC1662BinarySerialDevice.sendMsg(C:\BA\Software_projects\PIC\1510\8.5.18_ver_1_f\BA1510_GUI_1.1.11\atpLib\Devices\RFC1662Device\RFC1662BinarySerialDevice.cs:107) [INFO] - sending 6
2018-06-13 15:20:35,584 [26] atpLib.Scenarios.SingleMessageSingleDeviceScenario.internalRun(C:\BA\Software_projects\PIC\1510\8.5.18_ver_1_f\BA1510_GUI_1.1.11\atpLib\Scenarios\SingleMessageSingleDeviceScenario.cs:68) [ERROR] - The port is closed.
2018-06-13 15:20:35,616 [24] atpLib.Scenarios.Scenario.run(C:\BA\Software_projects\PIC\1510\8.5.18_ver_1_f\BA1510_GUI_1.1.11\atpLib\Scenarios\Scenario.cs:126) [ERROR] - Internal Scenario Error
System.InvalidOperationException: The port is closed.
   at atpLib.Scenarios.SingleMessageSingleDeviceScenario.internalRun(CancellationToken ct) in C:\BA\Software_projects\PIC\1510\8.5.18_ver_1_f\BA1510_GUI_1.1.11\atpLib\Scenarios\SingleMessageSingleDeviceScenario.cs:line 69
   at atpLib.Scenarios.Scenario.<>c__DisplayClass23_0.<runTask>b__0() in C:\BA\Software_projects\PIC\1510\8.5.18_ver_1_f\BA1510_GUI_1.1.11\atpLib\Scenarios\Scenario.cs:line 180
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
2018-06-13 15:20:35,618 [24] mfe_gui.Scenarios.SoftwareUpdateScenario.internalRun(C:\BA\Software_projects\PIC\1510\8.5.18_ver_1_f\BA1510_GUI_1.1.11\MFE_gui\Scenarios\SoftwareUpdateScenario.cs:137) [ERROR] - error in "Software Update Scenario"
mfe_gui.Scenarios.SoftwareUpdateScenario+SoftwareUpdateException: Exception of type 'mfe_gui.Scenarios.SoftwareUpdateScenario+SoftwareUpdateException' was thrown.
   at mfe_gui.Scenarios.SoftwareUpdateScenario.internalRun(CancellationToken ct) in C:\BA\Software_projects\PIC\1510\8.5.18_ver_1_f\BA1510_GUI_1.1.11\MFE_gui\Scenarios\SoftwareUpdateScenario.cs:line 70
2018-06-13 15:20:35,642 [23] atpLib.Scenarios.Scenario.runTask(C:\BA\Software_projects\PIC\1510\8.5.18_ver_1_f\BA1510_GUI_1.1.11\atpLib\Scenarios\Scenario.cs:221) [INFO] - Scenario failed.
2018-06-13 15:20:36,508 [25] atpLib.Scenarios.Scenario.runTask(C:\BA\Software_projects\PIC\1510\8.5.18_ver_1_f\BA1510_GUI_1.1.11\atpLib\Scenarios\Scenario.cs:178) [INFO] - Running scenario "Software Update Scenario" - with timeout of: 2147483 seconds.
2018-06-13 15:20:36,523 [23] mfe_gui.Scenarios.SoftwareUpdateScenario.internalRun(C:\BA\Software_projects\PIC\1510\8.5.18_ver_1_f\BA1510_GUI_1.1.11\MFE_gui\Scenarios\SoftwareUpdateScenario.cs:66) [INFO] - Programming address: 0x2000
2018-06-13 15:20:36,523 [26] atpLib.Scenarios.Scenario.runTask(C:\BA\Software_projects\PIC\1510\8.5.18_ver_1_f\BA1510_GUI_1.1.11\atpLib\Scenarios\Scenario.cs:178) [INFO] - Running scenario "Send Line Scenario" - with timeout of: 10 seconds.
2018-06-13 15:20:36,523 [24] atpLib.Scenarios.SingleMessageSingleDeviceScenario.internalRun(C:\BA\Software_projects\PIC\1510\8.5.18_ver_1_f\BA1510_GUI_1.1.11\atpLib\Scenarios\SingleMessageSingleDeviceScenario.cs:27) [INFO] - sending a message of type: SetBootDataMessage
2018-06-13 15:20:36,523 [24] atpLib.Devices.RFC1662BinarySerialDevice.sendMsg(C:\BA\Software_projects\PIC\1510\8.5.18_ver_1_f\BA1510_GUI_1.1.11\atpLib\Devices\RFC1662Device\RFC1662BinarySerialDevice.cs:107) [INFO] - sending 6
2018-06-13 15:20:36,523 [24] atpLib.Scenarios.SingleMessageSingleDeviceScenario.internalRun(C:\BA\Software_projects\PIC\1510\8.5.18_ver_1_f\BA1510_GUI_1.1.11\atpLib\Scenarios\SingleMessageSingleDeviceScenario.cs:68) [ERROR] - The port is closed.
2018-06-13 15:20:36,555 [23] atpLib.Scenarios.Scenario.run(C:\BA\Software_projects\PIC\1510\8.5.18_ver_1_f\BA1510_GUI_1.1.11\atpLib\Scenarios\Scenario.cs:126) [ERROR] - Internal Scenario Error
System.InvalidOperationException: The port is closed.
   at atpLib.Scenarios.SingleMessageSingleDeviceScenario.internalRun(CancellationToken ct) in C:\BA\Software_projects\PIC\1510\8.5.18_ver_1_f\BA1510_GUI_1.1.11\atpLib\Scenarios\SingleMessageSingleDeviceScenario.cs:line 69
   at atpLib.Scenarios.Scenario.<>c__DisplayClass23_0.<runTask>b__0() in C:\BA\Software_projects\PIC\1510\8.5.18_ver_1_f\BA1510_GUI_1.1.11\atpLib\Scenarios\Scenario.cs:line 180
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
2018-06-13 15:20:36,555 [23] mfe_gui.Scenarios.SoftwareUpdateScenario.internalRun(C:\BA\Software_projects\PIC\1510\8.5.18_ver_1_f\BA1510_GUI_1.1.11\MFE_gui\Scenarios\SoftwareUpdateScenario.cs:137) [ERROR] - error in "Software Update Scenario"
mfe_gui.Scenarios.SoftwareUpdateScenario+SoftwareUpdateException: Exception of type 'mfe_gui.Scenarios.SoftwareUpdateScenario+SoftwareUpdateException' was thrown.
   at mfe_gui.Scenarios.SoftwareUpdateScenario.internalRun(CancellationToken ct) in C:\BA\Software_projects\PIC\1510\8.5.18_ver_1_f\BA1510_GUI_1.1.11\MFE_gui\Scenarios\SoftwareUpdateScenario.cs:line 70
2018-06-13 15:20:36,570 [25] atpLib.Scenarios.Scenario.runTask(C:\BA\Software_projects\PIC\1510\8.5.18_ver_1_f\BA1510_GUI_1.1.11\atpLib\Scenarios\Scenario.cs:221) [INFO] - Scenario failed.
2018-06-13 15:20:37,222 [26] atpLib.Scenarios.Scenario.runTask(C:\BA\Software_projects\PIC\1510\8.5.18_ver_1_f\BA1510_GUI_1.1.11\atpLib\Scenarios\Scenario.cs:178) [INFO] - Running scenario "Software Update Scenario" - with timeout of: 2147483 seconds.
2018-06-13 15:20:37,237 [25] mfe_gui.Scenarios.SoftwareUpdateScenario.internalRun(C:\BA\Software_projects\PIC\1510\8.5.18_ver_1_f\BA1510_GUI_1.1.11\MFE_gui\Scenarios\SoftwareUpdateScenario.cs:66) [INFO] - Programming address: 0x2000
2018-06-13 15:20:37,237 [23] atpLib.Scenarios.Scenario.runTask(C:\BA\Software_projects\PIC\1510\8.5.18_ver_1_f\BA1510_GUI_1.1.11\atpLib\Scenarios\Scenario.cs:178) [INFO] - Running scenario "Send Line Scenario" - with timeout of: 10 seconds.
2018-06-13 15:20:37,237 [24] atpLib.Scenarios.SingleMessageSingleDeviceScenario.internalRun(C:\BA\Software_projects\PIC\1510\8.5.18_ver_1_f\BA1510_GUI_1.1.11\atpLib\Scenarios\SingleMessageSingleDeviceScenario.cs:27) [INFO] - sending a message of type: SetBootDataMessage
2018-06-13 15:20:37,237 [24] atpLib.Devices.RFC1662BinarySerialDevice.sendMsg(C:\BA\Software_projects\PIC\1510\8.5.18_ver_1_f\BA1510_GUI_1.1.11\atpLib\Devices\RFC1662Device\RFC1662BinarySerialDevice.cs:107) [INFO] - sending 6
2018-06-13 15:20:37,237 [24] atpLib.Scenarios.SingleMessageSingleDeviceScenario.internalRun(C:\BA\Software_projects\PIC\1510\8.5.18_ver_1_f\BA1510_GUI_1.1.11\atpLib\Scenarios\SingleMessageSingleDeviceScenario.cs:68) [ERROR] - The port is closed.
2018-06-13 15:20:37,269 [25] atpLib.Scenarios.Scenario.run(C:\BA\Software_projects\PIC\1510\8.5.18_ver_1_f\BA1510_GUI_1.1.11\atpLib\Scenarios\Scenario.cs:126) [ERROR] - Internal Scenario Error
System.InvalidOperationException: The port is closed.
   at atpLib.Scenarios.SingleMessageSingleDeviceScenario.internalRun(CancellationToken ct) in C:\BA\Software_projects\PIC\1510\8.5.18_ver_1_f\BA1510_GUI_1.1.11\atpLib\Scenarios\SingleMessageSingleDeviceScenario.cs:line 69
   at atpLib.Scenarios.Scenario.<>c__DisplayClass23_0.<runTask>b__0() in C:\BA\Software_projects\PIC\1510\8.5.18_ver_1_f\BA1510_GUI_1.1.11\atpLib\Scenarios\Scenario.cs:line 180
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
2018-06-13 15:20:37,269 [25] mfe_gui.Scenarios.SoftwareUpdateScenario.internalRun(C:\BA\Software_projects\PIC\1510\8.5.18_ver_1_f\BA1510_GUI_1.1.11\MFE_gui\Scenarios\SoftwareUpdateScenario.cs:137) [ERROR] - error in "Software Update Scenario"
mfe_gui.Scenarios.SoftwareUpdateScenario+SoftwareUpdateException: Exception of type 'mfe_gui.Scenarios.SoftwareUpdateScenario+SoftwareUpdateException' was thrown.
   at mfe_gui.Scenarios.SoftwareUpdateScenario.internalRun(CancellationToken ct) in C:\BA\Software_projects\PIC\1510\8.5.18_ver_1_f\BA1510_GUI_1.1.11\MFE_gui\Scenarios\SoftwareUpdateScenario.cs:line 70
2018-06-13 15:20:37,284 [26] atpLib.Scenarios.Scenario.runTask(C:\BA\Software_projects\PIC\1510\8.5.18_ver_1_f\BA1510_GUI_1.1.11\atpLib\Scenarios\Scenario.cs:221) [INFO] - Scenario failed.
2018-06-13 15:20:46,200 [24] atpLib.Scenarios.Scenario.runTask(C:\BA\Software_projects\PIC\1510\8.5.18_ver_1_f\BA1510_GUI_1.1.11\atpLib\Scenarios\Scenario.cs:178) [INFO] - Running scenario "Software Update Scenario" - with timeout of: 2147483 seconds.
2018-06-13 15:20:46,216 [25] mfe_gui.Scenarios.SoftwareUpdateScenario.internalRun(C:\BA\Software_projects\PIC\1510\8.5.18_ver_1_f\BA1510_GUI_1.1.11\MFE_gui\Scenarios\SoftwareUpdateScenario.cs:66) [INFO] - Programming address: 0x2000
2018-06-13 15:20:46,216 [26] atpLib.Scenarios.Scenario.runTask(C:\BA\Software_projects\PIC\1510\8.5.18_ver_1_f\BA1510_GUI_1.1.11\atpLib\Scenarios\Scenario.cs:178) [INFO] - Running scenario "Send Line Scenario" - with timeout of: 10 seconds.
2018-06-13 15:20:46,216 [23] atpLib.Scenarios.SingleMessageSingleDeviceScenario.internalRun(C:\BA\Software_projects\PIC\1510\8.5.18_ver_1_f\BA1510_GUI_1.1.11\atpLib\Scenarios\SingleMessageSingleDeviceScenario.cs:27) [INFO] - sending a message of type: SetBootDataMessage
2018-06-13 15:20:46,216 [23] atpLib.Devices.RFC1662BinarySerialDevice.sendMsg(C:\BA\Software_projects\PIC\1510\8.5.18_ver_1_f\BA1510_GUI_1.1.11\atpLib\Devices\RFC1662Device\RFC1662BinarySerialDevice.cs:107) [INFO] - sending 6
2018-06-13 15:20:46,216 [23] atpLib.Scenarios.SingleMessageSingleDeviceScenario.internalRun(C:\BA\Software_projects\PIC\1510\8.5.18_ver_1_f\BA1510_GUI_1.1.11\atpLib\Scenarios\SingleMessageSingleDeviceScenario.cs:68) [ERROR] - The port is closed.
2018-06-13 15:20:46,247 [25] atpLib.Scenarios.Scenario.run(C:\BA\Software_projects\PIC\1510\8.5.18_ver_1_f\BA1510_GUI_1.1.11\atpLib\Scenarios\Scenario.cs:126) [ERROR] - Internal Scenario Error
System.InvalidOperationException: The port is closed.
   at atpLib.Scenarios.SingleMessageSingleDeviceScenario.internalRun(CancellationToken ct) in C:\BA\Software_projects\PIC\1510\8.5.18_ver_1_f\BA1510_GUI_1.1.11\atpLib\Scenarios\SingleMessageSingleDeviceScenario.cs:line 69
   at atpLib.Scenarios.Scenario.<>c__DisplayClass23_0.<runTask>b__0() in C:\BA\Software_projects\PIC\1510\8.5.18_ver_1_f\BA1510_GUI_1.1.11\atpLib\Scenarios\Scenario.cs:line 180
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
2018-06-13 15:20:46,247 [25] mfe_gui.Scenarios.SoftwareUpdateScenario.internalRun(C:\BA\Software_projects\PIC\1510\8.5.18_ver_1_f\BA1510_GUI_1.1.11\MFE_gui\Scenarios\SoftwareUpdateScenario.cs:137) [ERROR] - error in "Software Update Scenario"
mfe_gui.Scenarios.SoftwareUpdateScenario+SoftwareUpdateException: Exception of type 'mfe_gui.Scenarios.SoftwareUpdateScenario+SoftwareUpdateException' was thrown.
   at mfe_gui.Scenarios.SoftwareUpdateScenario.internalRun(CancellationToken ct) in C:\BA\Software_projects\PIC\1510\8.5.18_ver_1_f\BA1510_GUI_1.1.11\MFE_gui\Scenarios\SoftwareUpdateScenario.cs:line 70
2018-06-13 15:20:46,263 [24] atpLib.Scenarios.Scenario.runTask(C:\BA\Software_projects\PIC\1510\8.5.18_ver_1_f\BA1510_GUI_1.1.11\atpLib\Scenarios\Scenario.cs:221) [INFO] - Scenario failed.
2018-06-13 15:21:01,523 [1] atpLib.Devices.SerialDevice.connect(C:\BA\Software_projects\PIC\1510\8.5.18_ver_1_f\BA1510_GUI_1.1.11\atpLib\Devices\SerialDevice.cs:46) [ERROR] - error oppening port "COM1"
System.IO.IOException: The port 'COM1' does not exist.
   at System.IO.Ports.InternalResources.WinIOError(Int32 errorCode, String str)
   at System.IO.Ports.SerialStream..ctor(String portName, Int32 baudRate, Parity parity, Int32 dataBits, StopBits stopBits, Int32 readTimeout, Int32 writeTimeout, Handshake handshake, Boolean dtrEnable, Boolean rtsEnable, Boolean discardNull, Byte parityReplace)
   at System.IO.Ports.SerialPort.Open()
   at atpLib.Devices.SerialDevice.connect() in C:\BA\Software_projects\PIC\1510\8.5.18_ver_1_f\BA1510_GUI_1.1.11\atpLib\Devices\SerialDevice.cs:line 41
2018-06-13 15:21:10,085 [1] atpLib.Devices.SerialDevice.connect(C:\BA\Software_projects\PIC\1510\8.5.18_ver_1_f\BA1510_GUI_1.1.11\atpLib\Devices\SerialDevice.cs:46) [ERROR] - error oppening port "COM1"
System.IO.IOException: The port 'COM1' does not exist.
   at System.IO.Ports.InternalResources.WinIOError(Int32 errorCode, String str)
   at System.IO.Ports.SerialStream..ctor(String portName, Int32 baudRate, Parity parity, Int32 dataBits, StopBits stopBits, Int32 readTimeout, Int32 writeTimeout, Handshake handshake, Boolean dtrEnable, Boolean rtsEnable, Boolean discardNull, Byte parityReplace)
   at System.IO.Ports.SerialPort.Open()
   at atpLib.Devices.SerialDevice.connect() in C:\BA\Software_projects\PIC\1510\8.5.18_ver_1_f\BA1510_GUI_1.1.11\atpLib\Devices\SerialDevice.cs:line 41
